### ISSUE TITLE
Run EOSIO Explorer as service

### ISSUE THREAD

**Issue by bert2002** [EOSIO/eosio-explorer#128]
Hi,
is it possible to to run eosio explorer as a service on a server? I have my own Nodeos cluster and MongoDB and would like to run the gui as a application in a webserver (not as gui on the client). 
Is that something on the roadmap? 

Many thanks,
bert

**Comment by jcardenas9x** [comment]
Hello bert, thanks for your interest in using the EOSIO Explorer.

It is already possible to run EOSIO Explorer as a web service on your own server if you want to.

Simply place the application on your web server and run:
```
eosio-explorer init --server-mode
```
When prompted for your choice of `nodeos` and MongoDB connection endpoints, you should supply the endpoints belonging to your `nodeos` cluster and MongoDB service.

The tool will launch on `localhost` at the default ports, so please be aware that you should make any configuration changes as needed so you can access the tool from your web server properly.

**Comment by bert2002** [comment]
Hey, thanks a lot. 
Seems its a bit more work to figure out how to use it without docker at all (CDT not tested).

Just in case someone is interested:
```
npm install yarn -g
git clone https://github.com/EOSIO/eosio-explorer
cd eosio-explorer
yarn install
yarn run react-app-rewired build
yarn start
```
Wait a bit and then the application is ready on port 3000 (even so it says its on 5111 in the stdout).

I tried to find the place where I can change the default configuration for the Connected Node and MongoDB settings and I think they are in `.env.local`, but its not possible to change the host and add credentials for MongoDB. Will that added later?

Thanks,
bert

**Comment by varshajnagaraja** [comment]
MongoDB credentials can be add added to 'MONGODB_PATH' URL in init_config.file, which is then copied to .env.local file when you run the `eosio-explorer init` command
