### ISSUE TITLE
Installed globally, Permission denied

### ISSUE THREAD

**Issue by sgehrman** [EOSIO/eosio-explorer#130]
$ eosio-explorer
 
/home/steve/eosio_explorer_config.json does not exist, calling init..
 
=========================
Welcome to EOSIO Explorer
=========================

Please select one of the following options by typing 1 or 2: 
1. Start the tool by connecting to default Nodeos and MongoDB endpoints.
2. Start the tool by connecting to existing Nodeos and MongoDB endpoints.
1
Starting tool with default endpoints...
===============================
INITIALISING CONFIG IN PACKAGES
===============================
cp: cannot create regular file '/usr/lib/node_modules/eosio-explorer/config.file.local': Permission denied

**Comment by FarhanQureshi19** [comment]
run with root privileges
sudo eosio-explorer
